import type { Product, Category } from "./types";

export const CATEGORIES: Category[] = [
  {
    id: "electronics",
    name: "Electronics",
    description: "Latest tech gadgets and devices",
    image: "/assets/categories/electronics.png",
    count: 24,
  },
  {
    id: "smart-home",
    name: "Smart Home",
    description: "Connected living solutions",
    image: "/assets/categories/smart-home.png",
    count: 18,
  },
  {
    id: "audio",
    name: "Audio & Speakers",
    description: "Premium sound systems",
    image: "/assets/categories/audio-speakers.png",
    count: 15,
  },
  {
    id: "furniture",
    name: "Furniture",
    description: "Modern home furniture",
    image: "/assets/categories/furniture.png",
    count: 22,
  },
  {
    id: "lighting",
    name: "Lighting",
    description: "Smart and ambient lighting",
    image: "/assets/categories/lighting.png",
    count: 12,
  },
];

export const PRODUCTS: Product[] = [
  {
    id: "prod-1",
    name: "Premium Wireless Headphones",
    description:
      "Advanced noise-canceling headphones with 30-hour battery life",
    price: 299,
    originalPrice: 399,
    image: "/assets/products/headphones.png",
    images: [
      "/assets/products/headphones.png",
      "/assets/products/headphones.png",
    ],
    category: "electronics",
    rating: 4.8,
    reviews: 342,
    variants: {
      colors: ["Black", "Silver", "Gold", "Blue"],
      sizes: ["One Size"],
    },
    inStock: true,
  },
  {
    id: "prod-2",
    name: "Smart Home Hub",
    description: "Control all your smart devices from one central hub",
    price: 129,
    image: "/assets/products/hub.png",
    images: ["/assets/products/hub.png", "/assets/products/hub.png"],
    category: "smart-home",
    rating: 4.6,
    reviews: 218,
    variants: {
      colors: ["White", "Black", "Gray"],
      sizes: ["One Size"],
    },
    inStock: true,
  },
  {
    id: "prod-3",
    name: "Portable Bluetooth Speaker",
    description: "Waterproof speaker with 12-hour battery and premium sound",
    price: 79,
    originalPrice: 99,
    image: "/assets/products/speaker.png",
    images: ["/assets/products/speaker.png", "/assets/products/speaker.png"],
    category: "audio",
    rating: 4.5,
    reviews: 456,
    variants: {
      colors: ["Black", "Red", "Blue", "Gray"],
      sizes: ["One Size"],
    },
    inStock: true,
  },
  {
    id: "prod-4",
    name: "Modern Desk Lamp",
    description: "LED desk lamp with adjustable brightness and USB charging",
    price: 49,
    image: "/assets/products/lamp.png",
    images: ["/assets/products/lamp.png", "/assets/products/lamp.png"],
    category: "lighting",
    rating: 4.7,
    reviews: 189,
    variants: {
      colors: ["Black", "White", "Gold"],
      sizes: ["One Size"],
    },
    inStock: true,
  },
  {
    id: "prod-5",
    name: "Ergonomic Office Chair",
    description: "Premium office chair with lumbar support and breathable mesh",
    price: 399,
    originalPrice: 549,
    image: "/assets/products/chair.png",
    images: ["/assets/products/chair.png", "/assets/products/chair.png"],
    category: "furniture",
    rating: 4.9,
    reviews: 267,
    variants: {
      colors: ["Black", "Gray", "White"],
      sizes: ["One Size"],
    },
    inStock: true,
  },
  {
    id: "prod-6",
    name: "Smart Thermostat",
    description: "WiFi-enabled thermostat with learning capabilities",
    price: 199,
    image: "/assets/products/thermostat.png",
    images: [
      "/assets/products/thermostat.png",
      "/assets/products/thermostat.png",
    ],
    category: "smart-home",
    rating: 4.4,
    reviews: 134,
    variants: {
      colors: ["White", "Black"],
      sizes: ["One Size"],
    },
    inStock: true,
  },
];
