import type { Product, Category } from "./types"

export const CATEGORIES: Category[] = [
  {
    id: "electronics",
    name: "Electronics",
    description: "Latest tech gadgets and devices",
    image: "/modern-tech-electronics.jpg",
    count: 24,
  },
  {
    id: "smart-home",
    name: "Smart Home",
    description: "Connected living solutions",
    image: "/smart-home-devices.jpg",
    count: 18,
  },
  {
    id: "audio",
    name: "Audio & Speakers",
    description: "Premium sound systems",
    image: "/premium-speaker-audio.jpg",
    count: 15,
  },
  {
    id: "furniture",
    name: "Furniture",
    description: "Modern home furniture",
    image: "/modern-minimalist-furniture.jpg",
    count: 22,
  },
  {
    id: "lighting",
    name: "Lighting",
    description: "Smart and ambient lighting",
    image: "/modern-lighting-lamps.jpg",
    count: 12,
  },
]

export const PRODUCTS: Product[] = [
  {
    id: "prod-1",
    name: "Premium Wireless Headphones",
    description: "Advanced noise-canceling headphones with 30-hour battery life",
    price: 299,
    originalPrice: 399,
    image: "/premium-wireless-headphones.png",
    images: ["/premium-wireless-headphones-front.jpg", "/premium-wireless-headphones-side.jpg"],
    category: "electronics",
    rating: 4.8,
    reviews: 342,
    variants: {
      colors: ["Black", "Silver", "Gold", "Blue"],
      sizes: ["One Size"],
    },
    inStock: true,
  },
  {
    id: "prod-2",
    name: "Smart Home Hub",
    description: "Control all your smart devices from one central hub",
    price: 129,
    image: "/smart-home-hub.png",
    images: ["/smart-home-hub-front.jpg", "/smart-home-hub-display.jpg"],
    category: "smart-home",
    rating: 4.6,
    reviews: 218,
    variants: {
      colors: ["White", "Black", "Gray"],
      sizes: ["One Size"],
    },
    inStock: true,
  },
  {
    id: "prod-3",
    name: "Portable Bluetooth Speaker",
    description: "Waterproof speaker with 12-hour battery and premium sound",
    price: 79,
    originalPrice: 99,
    image: "/portable-bluetooth-speaker.jpg",
    images: ["/portable-speaker-front.jpg", "/portable-speaker-compact.jpg"],
    category: "audio",
    rating: 4.5,
    reviews: 456,
    variants: {
      colors: ["Black", "Red", "Blue", "Gray"],
      sizes: ["One Size"],
    },
    inStock: true,
  },
  {
    id: "prod-4",
    name: "Modern Desk Lamp",
    description: "LED desk lamp with adjustable brightness and USB charging",
    price: 49,
    image: "/modern-led-desk-lamp.jpg",
    images: ["/desk-lamp-bright.jpg", "/desk-lamp-dim.jpg"],
    category: "lighting",
    rating: 4.7,
    reviews: 189,
    variants: {
      colors: ["Black", "White", "Gold"],
      sizes: ["One Size"],
    },
    inStock: true,
  },
  {
    id: "prod-5",
    name: "Ergonomic Office Chair",
    description: "Premium office chair with lumbar support and breathable mesh",
    price: 399,
    originalPrice: 549,
    image: "/ergonomic-office-chair-modern.jpg",
    images: ["/placeholder.svg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
    category: "furniture",
    rating: 4.9,
    reviews: 267,
    variants: {
      colors: ["Black", "Gray", "White"],
      sizes: ["One Size"],
    },
    inStock: true,
  },
  {
    id: "prod-6",
    name: "Smart Thermostat",
    description: "WiFi-enabled thermostat with learning capabilities",
    price: 199,
    image: "/smart-thermostat-device.jpg",
    images: ["/placeholder.svg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
    category: "smart-home",
    rating: 4.4,
    reviews: 134,
    variants: {
      colors: ["White", "Black"],
      sizes: ["One Size"],
    },
    inStock: true,
  },
  {
    id: "prod-7",
    name: "Standing Desk",
    description: "Adjustable height standing desk for flexible workspace",
    price: 599,
    originalPrice: 799,
    image: "/placeholder.svg?height=400&width=400",
    images: ["/placeholder.svg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
    category: "furniture",
    rating: 4.6,
    reviews: 198,
    variants: {
      colors: ["Natural Wood", "White", "Black"],
      sizes: ["120cm", "140cm", "160cm"],
    },
    inStock: true,
  },
  {
    id: "prod-8",
    name: "4K Webcam",
    description: "Professional 4K webcam with auto-focus and noise-canceling mic",
    price: 149,
    image: "/placeholder.svg?height=400&width=400",
    images: ["/placeholder.svg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
    category: "electronics",
    rating: 4.7,
    reviews: 156,
    variants: {
      colors: ["Black", "Silver"],
      sizes: ["One Size"],
    },
    inStock: true,
  },
  {
    id: "prod-9",
    name: "Smart Door Lock",
    description: "Keyless entry with fingerprint and app control",
    price: 179,
    image: "/placeholder.svg?height=400&width=400",
    images: ["/placeholder.svg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
    category: "smart-home",
    rating: 4.5,
    reviews: 142,
    variants: {
      colors: ["Black", "Silver"],
      sizes: ["One Size"],
    },
    inStock: true,
  },
  {
    id: "prod-10",
    name: "Ambient Light Strip",
    description: "RGB light strips with app control and music sync",
    price: 39,
    image: "/placeholder.svg?height=400&width=400",
    images: ["/placeholder.svg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
    category: "lighting",
    rating: 4.3,
    reviews: 267,
    variants: {
      colors: ["RGB Multi-color"],
      sizes: ["2m", "5m", "10m"],
    },
    inStock: true,
  },
]
